examples/yaml/tw-pywrap-e2e.yml
setup.py

- Add back in Tower GH Action
- Update repo url and version in setup

Merge latest changes from dev

---

README.md

Addresses #31 to add more detail on using e2e yaml example and the env variables required to be set.

docs: Add detail on using e2e yaml and env variables

---

environment.yml

Closes https://github.com/seqeralabs/twkit/issues/39

Remove additional bioconda channel from Conda environment.yml

---

twkit/cli.py
twkit/tower.py

Adds a --dryrun feature for use in development/testing

Adds --dryrun

---

twkit/tower.py

Should close #37 
I haven't been able to write a test yet.

Handle any strings with dollar sign as env should be interpreted

---

README.md
tests/unit/test_helper.py
twkit/cli.py
twkit/helper.py
twkit/overwrite.py

Add info on how to supply `tw` CLI option of `-Djavax.net.ssl.trustStore=/absolute/path/to/cacerts` to `twkit`.

Update docs on using custom SSL certificate

---

seqerakit/seqeraplatform.py

Add error handling for environment variables to check:
- If an argument is an environment variable, check value exists
- If not, raise an error with name of environment variable
Also refactored the `SeqeraPlatform` class to clean up methods, including `_tw_run`.

Error handling for environment variables not set 

---

LICENSE.txt
seqerakit/cli.py
seqerakit/computeenvs.py
seqerakit/helper.py
seqerakit/overwrite.py
seqerakit/pipelines.py
seqerakit/seqeraplatform.py
seqerakit/utils.py
setup.py

docs: update license to apache 2.0

---

seqerakit/seqeraplatform.py
tests/unit/test_seqeraplatform.py

Changes:
- Now detects environment variables within and between strings for more
complex variables
- Raises error if an environment variable is missing
- Passes string referring to environment variable transparently to
prevent accidental variable leakage.

Fix handling of complex environment variables

---

seqerakit/helper.py

fix: multi yaml parsing with same keys

---

seqerakit/cli.py
seqerakit/seqeraplatform.py

- Allow bash redirection and shell-specific syntax when running with `seqerakit`
- Support for importing the CLI interface as a module and running with yaml

Support for bash specific syntax and sys.argv

---

README.md
environment.yml

After https://github.com/bioconda/bioconda-recipes/pull/44260, we should just the conda package. If not, I do not think we should be encouraging hybrid conda/ pip usage.

Simplify install

---

README.md
templates/actions.yml
templates/compute-envs.yml
templates/credentials.yml
templates/launch.yml
templates/pipelines.yml

Closes #92. Adds detail about:
- New `--info` arg
- Using `seqerakit` specific YAML options like `params` vs `params-file`, `file-path`, and `overwrite` with examples

docs: add details on yaml config options, new info arg

---

README.md
templates/compute-envs.yml

Update docs for installation, YAML definitions and templates

---

seqerakit/seqeraplatform.py
tests/unit/test_seqeraplatform.py

seqerakit missed some errors raised by the cli and continued on. This PR fixes that bug and raises the error in the console.

fix: catch errors more reliably

---

seqerakit/helper.py

Fix for #144, updates logic in `parse_all_yaml()` for merged data from multiple input YAMLs

fix: type error when using params dict in yaml

---

setup.py

Release v0.4.8

---

seqerakit/seqeraplatform.py
tests/unit/test_seqeraplatform.py

Fixes #169 and issues reported by Engineering team when specifying `$TW_AGENT_WORK` in the YAML config, these 
variables should be treated as literal strings and not be interpolated. Added special handling to escape these variables correctly when constructing the command line arguments.
Example usage:
```yaml
credentials:
- name: 'test-agent'
type: 'agent'
workspace: 'seqeralabs/testing'
connection-id: '123456-789012'
work-dir: '$TW_AGENT_WORK' 
```

fix: handling for API vars and escaped vars

---

.prettierignore
README.md
seqerakit/cli.py
templates/actions.yml
templates/compute-envs.yml
templates/credentials.yml
templates/datasets.yml
templates/labels.yml
templates/launch.yml
templates/pipelines.yml
templates/secrets.yml

Fixes #161, we can already support creation of resources in user workspaces but the overwrite logic was interfering with this. This logic has been updated and we've added documentation on how to use personal workspaces.

Fix support for user/personal workspaces

---

seqerakit/cli.py

uses pathlib glob to find yaml files in directories.
Also includes explicit files and stdin

Recursively find yaml files in directories

---

README.md

Adds some very quick documentation for using environment variables and `--env-file`.

Document use of environment variables in the README.md
