seqeralabs/seqerakit

- twkit/utils.py
Changes:
- Temp YAML is created with double quotes which should allow shell to evaluate environment variables.
- Environment variables in YAML are evaluated while creating tmp file which should allow dynamic naming. 
- Only applies to params.
Fixes #38
> Evaluate environment variables in params block

- tests/unit/test_helper.py
- twkit/cli.py
- twkit/helper.py
Adds support for passing multiple yaml files to `twkit` in no particular order of resource creation.
To test: 
Create 3 yamls:
```
datasets:
- name: 'test_dataset1' 
description: 'My test dataset 1'  
header: true 
workspace: 'twkit-e2e/showcase'
file-path: './examples/yaml/datasets/rnaseq_samples.csv'
overwrite: True  
```
```
launch:
- name: 'nf-core-rnaseq-launchpad'
workspace: 'twkit-e2e/showcase'
pipeline: 'nf-core-rnaseq'
```
```
pipelines:
- name: 'nf-core-rnaseq'
url: 'https://github.com/nf-core/rnaseq'
workspace: 'twkit-e2e/showcase'
description: 'RNA sequencing analysis pipeline using STAR, RSEM, HISAT2 or Salmon with gene/isoform counts and extensive quality control.'
compute-env: 'seqera_aws_ireland_fusionv2_nvme'
work-dir: 's3://seqeralabs-showcase'
profile: 'test'
revision: …
```
> Support multiple input files

- README.md
- tests/unit/test_helper.py
- twkit/cli.py
- twkit/helper.py
- twkit/overwrite.py
Adds support for a `--delete` flag where if supplied to `twkit` with YAML(s), will recursively delete all resources instead of create them. For example, if you create organization -> workspace -> team -> credentials -> compute-env -> pipeline. When supplying `twkit file.yaml --delete`, the tool will delete pipeline -> compute-env -> credentials -> team -> workspace -> organization. 
Leverages existing functionality we had for deleting resources in `overwrite.py`, specifically the `delete_resource()` method called in `handle_overwrite`.
> Recursively delete from yaml

- environment.yml
- setup.py
The python dependency is too tight right now, I couldn't get the environment to create on the mac (even with CONDA_SUBDIR):
```
Could not solve for environment specs
The following package could not be installed
└─ python 3.10.9*  is uninstallable because it requires
└─ libffi >=3.4,<4.0a0 , which conflicts with any installable versions previously reported.
```
From the README we just need 3.8 minimum, right? 
(this did work for me)
> Relax python dependency

- README.md
- twkit/cli.py
Use `--cli "--insecure"` instead of `--cli --insecure` for clarity and better readability
> refactor: enclose tw cli options in double quotes to twkit

- README.md
- tests/unit/test_tower.py
- twkit/cli.py
- twkit/tower.py
- twkit/utils.py
Re #49 where `--dryrun` returns JSON errors. Additionally adds test for `--dryrun` and another for CLI args like custom SSL cert stores.
> Fix broken dryrun option

- tests/unit/test_tower.py
- twkit/tower.py
Adding a participant produced a slightly different error message.
From:
Resource already exists
To:
Already a participant
Changing to case insensitive and adding an extra regex group caught it.
Added additional test for new scenario.
> Ignore existing participant error

- seqerakit/cli.py
Allows the main method to be called with custom arguments when imported as a module, which is necessary for cases like providing `--help` from another script or an interactive session.
> Fix argparse in CLI interface

- seqerakit/cli.py
- seqerakit/seqeraplatform.py
Small fix to the way we catch custom exceptions to pass the error message in the raise statement and log it before exiting downstream.
> fix: handling of cli errors and custom exp

- .github/workflows/overwrite-testing.yml
- seqerakit/utils.py
- tests/e2e/aws-e2e.yml
Addresses #87.
The `overwrite` class contains a method where it calls a generic utility function written to take json data, and a key-value pair to check if the value exists within a nested json. If an environment variable was specified for the `name: ` key in entities, it was not being resolved correctly when running this utility function. This has been fixed.
To test, run `seqerakit test.yaml` with the following and set $SEQERA_ORGANIZATION_NAME to anything:
```
organizations:
- name: '$SEQERA_ORGANIZATION_NAME'
full-name: '$SEQERA_ORGANIZATION_NAME'
description: 'Organization created E2E with seqerakit CLI scripting'
location: 'Global'
website: 'https://seqera.io/'
overwrite: True
```
Re-run:
```
DEBUG:root: Overwrite is set to 'True' for organizations
DEBUG:root: Running command: tw …
```
> FIx overwrite

- .github/workflows/python-testing.yml
- README.md
- seqerakit/helper.py
- seqerakit/utils.py
- tests/unit/test_helper.py
Addresses #45 to support both `params` and `params-file` for `tw pipelines` and `tw launch`.
If both `params:` and `params-file:` path is specified in either block, a temp YAML containing combined values from both will be generated. If there are duplicate key-value pairs, the `params:` in YAML takes precedence.
For example:
```yaml
launch:
- name: 'nf-core-rnaseq-skit-params-test'
pipeline: 'nf-core-rnaseq'
workspace: 'scidev/testing'
params-file: './params/nf_core_rnaseq_params.yml' # contains outdir: "s3://scidev-eu-west-1/nf-core-rnaseq/results"
params:
skip_gtf_filter: true
```
The resultant parameters are:
```yaml
outdir: "s3://scidev-eu-west-1/nf-core-rnaseq/results"
skip_gtf_filter: true
```
If you specify duplicate keys in the `params` block:
```yaml
launch:
- name: …
```
> feat: support params and params-file keys

- seqerakit/cli.py
- seqerakit/seqeraplatform.py
Addresses #4 with added error handling if no YAMLs provided.
Test with:
```
seqerakit --info
```
Or, in a Python script:
```
from seqerakit import seqeraplatform
tw = seqeraplatform.SeqeraPlatform()
print(tw.info())
```
> feat: add info flag and support for tw info

- seqerakit/cli.py
- seqerakit/helper.py
- tests/unit/test_helper.py
Closes #103 
Adds error handling for when an empty YAML file is provided in `helper.parse_all_yaml`.
> feat: add better error handling for empty yaml

- seqerakit/helper.py
- tests/unit/test_helper.py
Re #117
Avoid relying on `type` as dict name for `credentials`, `compute-envs`, and `actions` and instead allow it to be in any order of the dict but still correctly parse these blocks to use `type` to construct subcommand. Also add validation to ensure atleast `type`, `file-path` are provided.
Unit tests updated to test for this behaviour.
> fix: type parsing for ces,actions,credentials

- seqerakit/overwrite.py
Re #115
Fixes bug in keys used to retrieve identifier for workspaces and retrieving ID for workspace for deletion.
> fix: fix delete/overwrite bug with workspaces

- README.md
- seqerakit/__init__.py
- seqerakit/cli.py
Re #111 
- Adds flag to emit current version of seqerakit
- Refactor help flag to categorize seqerakit run commands vs YAML-specific processing commands
- Update README and add minimum version of CLI required
> feat: add flag for emitting version info, refactor parseargs

- README.md
Re #109.
Adds detail to configuration about specifying `TOWER_API_ENDPOINT` when using Enterprise, based on user feedback.
> docs: api endpoint detail in config

- seqerakit/cli.py
- seqerakit/helper.py
- seqerakit/overwrite.py
- templates/labels.yml
Re #125 to allow users to add resource labels to workspaces
- Update `helper.py` to parse `labels` with generic `add` method
- Add helper methods in `overwrite.py` to handle deletion of labels by their id
- Add a template yaml for labels
> feat: add support for creating labels

- seqerakit/cli.py
- seqerakit/helper.py
- seqerakit/overwrite.py
- tests/unit/test_helper.py
Re #123
- Fixes method used to identify value associated with `name` key or `--name` argument and use value to identify duplicates 
- Disable any usage of overwrite method with `--dryrun`
Test with a yaml defining teams as following:
```yaml
teams:
- name: "launchers"
organization: "myorg"
description: "Users with launcher permissions"
overwrite: true
members:
- launcher@myorg.io
- name: "viewers"
organization: "myorg"
description: "Users with viewer permissions"
overwrite: true
members:
- viewer@myorg.io
```
Where running seqerakit will correctly provide dryrun output:
```console
$ seqerakit teams.yaml --dryrun
DEBUG:root:DRYRUN: Running command tw teams add --name launchers --organization myorg --description 'Users with launcher permissions'
DEBUG:root:DRYRUN: Running command tw teams …
```
> fix: fix duplicate name bug

- seqerakit/helper.py
- tests/unit/test_helper.py
Found with adding `members`, the result from `find_name()` returned none because the `--name` key does not exist. 
Resolved with defining keys to check membership for in items with strings or lists. Test with:
```yaml
members:
- user: 'esha.joshi+owner@seqera.io'
organization: '$TOWER_ORG_NAME'
overwrite: True
- user: 'esha.joshi+owner@seqera.io'
organization: '$TOWER_ORG_NAME'
overwrite: True
```
Where dryrun returns:
```
DEBUG:root:DRYRUN: Running command tw members add --user esha.joshi+owner@seqera.io --organization $TOWER_ORG_NAME
DEBUG:root:DRYRUN: Running command tw members add --user esha.joshi+maintain@seqera.io --organization $TOWER_ORG_NAME
```
> Fix uniqueness bug with dicts using keys other than name

- seqerakit/overwrite.py
- seqerakit/utils.py
Fix overwrite to use `organization` argument when generating list of workspaces in JSON data to use for deletion. Otherwise, there can be multiple workspaces of the same name across many organizations which will interfere with deletion.
> fix: generate json data for workspaces with org argument for deletion

- .github/workflows/teardown.yml
- README.md
- environment.yaml
re #150, removes conda `defaults` channel from README, `environment.yaml` and GH workflow channels.
> fix: remove defaults channel from install and build

- seqerakit/seqeraplatform.py
- tests/unit/test_seqeraplatform.py
Fix #149 to add handling if empty strings are provided as arguments. Throws a `ValueError` and indicates which arg/parameter was provided an empty string value for.
> fix: add handling for empty strings in key-value pairs of yaml

- seqerakit/cli.py
- seqerakit/seqeraplatform.py
- tests/unit/test_seqeraplatform.py
Fixes #151 to use Tw CLI options with `--cli` and also `--dryrun` when invoking the `info` method.
Test with:
```
$ seqerakit --info --cli="--url=https://cloud.seqera.io/api"
```
Should return:
```console      
INFO:root: Running command: tw --url=https://cloud.seqera.io/api info
Details
-------------------------+-----------------------------
Tower API endpoint      | https://cloud.seqera.io/api 
Tower API version       | 1.25.0                      
Tower version           | 24.2.0_cycle20              
CLI version             | 0.9.2 (39a2ec6)             
CLI minimum API version | 1.15                        
Authenticated user      | esha-joshi                  
System health status
---------------------------------------+----
Remote API server connection check    | OK 
Tower API …
```
> fix: improve logic to respect cli and dryrun flags with info

- seqerakit/cli.py
- seqerakit/overwrite.py
- seqerakit/seqeraplatform.py
- tests/unit/test_seqeraplatform.py
Re #152 to improve seqerakit reporting on errors and successes. 
With these changes, the  command invoked and subsequent stdout will be provided through logging by default, with improved error handling if the command fails.
Running the following YAML:
```yaml
launch:
- name: "hello-world-test-seqerakit"
pipeline: "https://github.com/nextflow-io/hello"
workspace: "scidev/testing"
compute-env: "seqera_aws_london_fusion_nvme"
```
Will return the following by default logging level of `INFO` upon success:
```
seqerakit example.yml       
INFO:root: Running command: tw launch --name hello-world-test-seqerakit --workspace scidev/testing --compute-env seqera_aws_london_fusion_nvme https://github.com/nextflow-io/hello
INFO:root: Command output: Workflow 3A8HdVzqtBDWST submitted at [scidev / …
```
> Report success and failures better in seqerakit

- seqerakit/cli.py
- seqerakit/helper.py
- tests/unit/test_helper.py
Adds a new flag, `--targets`, to the CLI interface to specify "targets" for creation in an omnibus YAML file with one or more resources defined. For example, with a YAML as such:
```yaml
workspaces:
- name: 'showcase'
organization: 'seqerakit_automation'
full-name: 'e2e_demo_showcase'
overwrite: True
labels:
- name: 'seqerakit'
value: 'seqerakit'
workspace: 'scidev/testing'
overwrite: True
pipelines:
- name: "hello-world-test-seqerakit"
url: "https://github.com/nextflow-io/hello"
workspace: "scidev/test"
compute-env: "seqera_aws_london_fusion_nvme"
revision: "master"
overwrite: True
```    
We can specify resources to create with:
```
$ seqerakit example.yml --targets pipelines
seqerakit example.yml --targets pipelines
INFO:root: Running command: tw -o json pipelines list -w …
```
> Add targets flag to specify resources for creation in input YAML

- README.md
- examples/python/launch_hello_world.py
- seqerakit/cli.py
- seqerakit/computeenvs.py
- seqerakit/seqeraplatform.py
- tests/unit/test_seqeraplatform.py
We needed a method of storing run info from the seqerakit CLI. After this change, you can use the '--json' flag to write the JSON return from the CLI to STDOUT. This can be captured and used in a different process or piped. This is enabled by a new command line flag, --json but should be possible when instantiating the SeqeraPlatform class in Python. The to_json kwarg is removed and replaced with this method so this might break some uses. The JSON is an attribute of the class and can be referenced whenever you use the SeqeraPlatform class.
BREAKING CHANGE: This could break anyone using the Python implementation with `to_json=True`. This is mainly [me](https://github.com/seqeralabs/showcase-automation/blob/528487f5d04d1207fa895d5ca9e398de2ecc0853/launch_pipelines.py#L154).
To use, try …
> feat(SeqeraPlatform): seqerakit can write JSON to stdout for detailed records

- seqerakit/cli.py
- seqerakit/seqeraplatform.py
Fixes #170. 
- Creates a separate instance of the `SeqeraPlatform` class for `Overwrite` to inherit without using the JSON option so we don't double up on `-o json`. The `Overwrite` class handles emitting output to JSON natively so we don't need this handling. 
- Modified `_execute_command` to respect `print_stdout` setting when JSON output is enabled. Previously, stdout would always be printed when processing JSON output, regardless of the `print_stdout` flag. This change ensures consistent behavior between JSON and non-JSON output modes.
> fix: handling for overwrite class without json output

- .pre-commit-config.yaml
- seqerakit/seqeraplatform.py
> fix: add correct handling for windows env vars

- seqerakit/seqeraplatform.py
Errors were being ignored in the tw cli output because it was checking for `"ERROR: "` but the error message is actually `"ERROR:"` with additional ANSI escape codes. This PR removes the space which correctly catches the error.
fixes #178
> fix: Correctly catches and raises errors from tw cli

- seqerakit/cli.py
- seqerakit/seqeraplatform.py
Alternative to #181 
Instead of parsing the env file in the class, it loads it into the environment.
The advantage is it's more broadly applicable (i.e. it works everywhere, the disadvantage is it's pretty blunt and just wipes out any existing environment variables.
Currently the `--env-file` takes precedence over the existing environment variables but this could be swapped.
> Use params file for environment variables

- seqerakit/cli.py
- seqerakit/seqeraplatform.py
- POC to test out support for an input file with variables defined and used for templating
- Modified `_check_env_vars()` to use a unified variables dictionary
- Variables from the YAML file will override environment variables if there are conflicts
With an example vars file called `vars.yaml`:
```yaml
EXECUTOR: gcp
COMPUTE_ENV_NAME: tower_cloud_testing_finland_fusionv2
ORGANIZATION_NAME: scidev
WORKSPACE_NAME: gcp
PIPELINE_PROFILE: test
```
And an `example.yaml` YAML using the variables:
```yaml
pipelines:
- name: "nf-core-rnaseq-$EXECUTOR"
url: "https://github.com/nf-core/rnaseq"
description: "RNA sequencing analysis pipeline using STAR, RSEM, HISAT2 or Salmon with gene/isoform counts and extensive quality control."
workspace: "$ORGANIZATION_NAME/$WORKSPACE_NAME"
compute-env: …
```
> Draft: add support for a variables file as input for templating

- seqerakit/cli.py
Adds support for specifying multiple CLI arguments using repeated `--cli` flags. This allows users to pass multiple CLI arguments to the Seqera Platform CLI in a more flexible way instead of provided a comma separated list.
> fix: support for multiple cli args provided via cli

- seqerakit/cli.py
Modifies how environment variables from `--env-file` are processed:
- Now properly expands environment variables in values (e.g., `$VAR` or `${VAR}`)
- Only updates explicitly defined variables instead of overwriting all environment variables in the session and preserves existing environment variables that aren't specified in the env file
Using `--env-file` with content:
```
DOCKERHUB_CREDENTIALS_NAME: "dockerhub_credentials"
DOCKERHUB_CREDENTIALS_USERNAME: "$DOCKERHUB_USER"
DOCKERHUB_CREDENTIALS_PASSWORD: "some_value"
```
- Will expand `$DOCKERHUB_CREDENTIALS_USERNAME` to its environment value
- Leaves all other environment variables unchanged
> fix: parsing of vars in input file with existing env

- seqerakit/cli.py
- seqerakit/seqeraplatform.py
- tests/unit/test_seqeraplatform.py
Re #194, I am not sure/I don't remember why we would check for specific strings in the first place but this generic approach allows us to catch all error cases.
> fix: catch and handle all non-zero exit codes

- seqerakit/cli.py
Adds an experimental option in CLI to specify a global `--overwrite` flag for all resources defined in input YAMLs.
> Add global overwrite option

- README.md
- seqerakit/cli.py
- seqerakit/helper.py
- seqerakit/overwrite.py
- templates/data-links.yml
- templates/studios.yml
- tests/unit/test_helper.py
- tests/unit/test_overwrite.py
> feat: add support for studios and data-links

- seqerakit/cli.py
- seqerakit/helper.py
- tests/unit/test_helper.py
This PR adds support for resolving dataset references in pipeline parameters. Users can now reference a dataset by name in their pipeline parameters, and seqerakit will automatically resolve it to the dataset URL.
- Added `resolve_dataset_reference` function to handle dataset URL resolution
- Created `process_params_dict` to standardize params handling across commands
- Added error handling for missing datasets and resolution failures and tests
> feat: resolve dataset names to urls if in params dict

- seqerakit/cli.py
- seqerakit/helper.py
- seqerakit/overwrite.py
The `on_exists` field in the YAML was being ignored by seqerakit because it was bypassed by the code path. This PR just reorders some stuff and fixes the issue.
> fix: on_exists inside YAML files is respected

- seqerakit/helper.py
- seqerakit/seqeraplatform.py
- seqerakit/utils.py
- tests/unit/test_seqeraplatform.py
When seqerakit encounters a null or None value when submitting tower-cli commands, it will skip and bypass those options to the tower-cli and therefore support can ignore empty values
This will fix #212
> feat: Remove null values from YAML input files

- seqerakit/overwrite.py
- tests/unit/test_overwrite.py
The overwrite behaviour ignored using multiple workspaces because the cached data just cached the contents and not the workspace ID. In this commit we add the workspace name to the key which will semi-uniqueify the cache and force an overwrite.
To do:
> feat: Handle multiple workspaces when using overwrite behaviour

- seqerakit/helper.py
- tests/unit/test_helper.py
Add support for including a `primary: true` option in CE YAMLs to create them but then set them to primary.
> feat: add support for setting CEs to primary
